#!/bin/bash

#Needed files (in same directory): antechamber_script, tleap-template, convert-to-tinker.py, defs-amber99sb.txt and amber99sb.prm
#Four letter code for
drug=$1
cd $drug
export PYTHONPATH=~/lib/python:$PYTHONPATH
drugu=`echo $drug | awk '{print toupper($0)}'`
#on the compute nodes "python" points to "/usr/bin/python" which doesn't seem to be able to handle parmed
/usr/local/bin/python ../convert-to-tinker.py $drug.prm7 2501 51 $drug.prm
#the 2.0 is the dihedral cutoff for declaring a "stiff" double bond
/usr/local/bin/python ../create-defs-solvation2.py $drug.prm7 $drugu 2501 defs-$drug.txt 51 solv-$drug.txt 2.0
#append amber parameters and definitions to create a complete parameter set for the protein-ligand system
cat ../amber99sb.prm $drug.prm > amber99sb-$drug.prm
cat ../defs-amber99sb.txt defs-$drug.txt > defs-amber99sb-$drug.txt
cat ../solvpar-seddd.txt solv-$drug.txt > solvpar-seddd-$drug.txt
cd ..
